builds:
- main: couchbase_exporter.go
  binary: couchbase_exporter
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - amd64
    - arm64

archive:
  format: tar.gz
  name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
  files:
    - LICENSE.txt